var exercises = [
  ["dumbbells","abs","weighted crunch","http://www.dumbbell-exercises.com/exercises/abdominals/images/1.gif"],
  ["dumbbells","abs","weighted leg raise","http://www.dumbbell-exercises.com/exercises/abdominals/images/2.gif"],
  ["dumbbells","abs","dumbbell side bend","http://www.dumbbell-exercises.com/exercises/abdominals/images/3.gif"],
  ["dumbbells","chest","bench press","http://www.dumbbell-exercises.com/exercises/chest/images/1.gif"],
  ["dumbbells","chest","bench press (neutral grip)","http://www.dumbbell-exercises.com/exercises/chest/images/2.gif"],
  ["dumbbells","chest","incline bench press","http://www.dumbbell-exercises.com/exercises/chest/images/3.gif"],
  ["dumbbells","chest","incline bench press (neutral grip)","http://www.dumbbell-exercises.com/exercises/chest/images/4.gif"],
  ["dumbbells","chest","decline bench press","http://www.dumbbell-exercises.com/exercises/chest/images/5.gif"],
  ["dumbbells","chest","lying fly","http://www.dumbbell-exercises.com/exercises/chest/images/6.gif"],
  ["dumbbells","chest","incline fly","http://www.dumbbell-exercises.com/exercises/chest/images/7.gif"],
  ["dumbbells","chest","straight-arm pull-over","http://www.dumbbell-exercises.com/exercises/chest/images/8.gif"],
  ["dumbbells","chest","bent-arm pull-over","http://www.dumbbell-exercises.com/exercises/chest/images/9.gif"],
  ["dumbbells","shoulders","palms-in shoulder press","http://www.dumbbell-exercises.com/exercises/shoulders/images/1.gif"],
  ["dumbbells","shoulders","back-supported palms-in shoulder press","http://www.dumbbell-exercises.com/exercises/shoulders/images/2.gif"],
  ["dumbbells","shoulders","palms-in alternated shoulder press","http://www.dumbbell-exercises.com/exercises/shoulders/images/3.gif"],
  ["dumbbells","shoulders","seated palms-in alternated shoulder press","http://www.dumbbell-exercises.com/exercises/shoulders/images/4.gif"],
  ["dumbbells","shoulders","shoulder press","http://www.dumbbell-exercises.com/exercises/shoulders/images/5.gif"],
  ["dumbbells","shoulders","seated shoulder press","http://www.dumbbell-exercises.com/exercises/shoulders/images/6.gif"],
  ["dumbbells","shoulders","back-supported shoulder press","http://www.dumbbell-exercises.com/exercises/shoulders/images/7.gif"],
  ["dumbbells","shoulders","lateral raise","http://www.dumbbell-exercises.com/exercises/shoulders/images/8.gif"],
  ["dumbbells","shoulders","bent-over one-arm deltoid raise","http://www.dumbbell-exercises.com/exercises/shoulders/images/9.gif"],
  ["dumbbells","shoulders","seated side lateral raise","http://www.dumbbell-exercises.com/exercises/shoulders/images/10.gif"],
  ["dumbbells","shoulders","bent-over rear deltoid raise","http://www.dumbbell-exercises.com/exercises/shoulders/images/11.gif"],
  ["dumbbells","shoulders","rear deltoid raise","http://www.dumbbell-exercises.com/exercises/shoulders/images/12.gif"],
  ["dumbbells","shoulders","rear deltoid circle","http://www.dumbbell-exercises.com/exercises/shoulders/images/13.gif"],
  ["dumbbells","shoulders","straight-arm front deltoid raise","http://www.dumbbell-exercises.com/exercises/shoulders/images/14.gif"],
  ["dumbbells","shoulders","upright row","http://www.dumbbell-exercises.com/exercises/shoulders/images/15.gif"],
  ["dumbbells","shoulders","front raise","http://www.dumbbell-exercises.com/exercises/shoulders/images/16.gif"],
  ["dumbbells","shoulders","shoulder shrug","http://www.dumbbell-exercises.com/exercises/shoulders/images/17.gif"],
  ["dumbbells","shoulders","push press","http://www.dumbbell-exercises.com/exercises/shoulders/images/18.gif"],
  ["dumbbells","shoulders","crouched rear deltoid row","http://www.dumbbell-exercises.com/exercises/shoulders/images/19.gif"],
  ["dumbbells","biceps","one-arm bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/1.gif"],
  ["dumbbells","biceps","alternated bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/2.gif"],
  ["dumbbells","biceps","inner-bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/3.gif"],
  ["dumbbells","biceps","bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/4.gif"],
  ["dumbbells","biceps","hammer curl","http://www.dumbbell-exercises.com/exercises/biceps/images/5.gif"],
  ["dumbbells","biceps","seated alternated bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/6.gif"],
  ["dumbbells","biceps","seated bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/7.gif"],
  ["dumbbells","biceps","incline alternated bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/8.gif"],
  ["dumbbells","biceps","incline bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/9.gif"],
  ["dumbbells","biceps","incline bicep bench curl","http://www.dumbbell-exercises.com/exercises/biceps/images/10.gif"],
  ["dumbbells","biceps","concentration bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/11.gif"],
  ["dumbbells","biceps","seated inner-bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/12.gif"],
  ["dumbbells","biceps","seated concentration curl","http://www.dumbbell-exercises.com/exercises/biceps/images/13.gif"],
  ["dumbbells","biceps","seated isolated dumbbell curl","http://www.dumbbell-exercises.com/exercises/biceps/images/14.gif"],
  ["dumbbells","biceps","preacher bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/15.gif"],
  ["dumbbells","biceps","preacher bicep curl (neutral grip)","http://www.dumbbell-exercises.com/exercises/biceps/images/16.gif"],
  ["dumbbells","biceps","bench alternated bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/17.gif"],
  ["dumbbells","biceps","supine bicep curl","http://www.dumbbell-exercises.com/exercises/biceps/images/18.gif"],
  ["dumbbells","triceps","triceps extension","http://www.dumbbell-exercises.com/exercises/triceps/images/1.gif"],
  ["dumbbells","triceps","one-arm tricep extension","http://www.dumbbell-exercises.com/exercises/triceps/images/2.gif"],
  ["dumbbells","triceps","seated triceps extension","http://www.dumbbell-exercises.com/exercises/triceps/images/3.gif"],
  ["dumbbells","triceps","triceps kickback","http://www.dumbbell-exercises.com/exercises/triceps/images/4.gif"],
  ["dumbbells","triceps","bent-over one-arm tricpes extension","http://www.dumbbell-exercises.com/exercises/triceps/images/5.gif"],
  ["dumbbells","triceps","lying triceps extension","http://www.dumbbell-exercises.com/exercises/triceps/images/6.gif"],
  ["dumbbells","triceps","triceps bench press","http://www.dumbbell-exercises.com/exercises/triceps/images/7.gif"],
  ["dumbbells","back","wide row","http://www.dumbbell-exercises.com/exercises/back/images/1.gif"],
  ["dumbbells","back","bent over row","http://www.dumbbell-exercises.com/exercises/back/images/2.gif"],
  ["dumbbells","back","kneeling one-arm row","http://www.dumbbell-exercises.com/exercises/back/images/3.gif"],
  ["dumbbells","back","one-arm row","http://www.dumbbell-exercises.com/exercises/back/images/4.gif"],
  ["dumbbells","back","dead lift","http://www.dumbbell-exercises.com/exercises/back/images/5.gif"],
  ["dumbbells","back","stiff-legged dead lift","http://www.dumbbell-exercises.com/exercises/back/images/6.gif"],
  ["dumbbells","back","bend to opposite foot","http://www.dumbbell-exercises.com/exercises/back/images/7.gif"],
  ["dumbbells","back","twisting bend to opposite foot","http://www.dumbbell-exercises.com/exercises/back/images/8.gif"],
  ["dumbbells","back","back fly","http://www.dumbbell-exercises.com/exercises/back/images/9.gif"],
  ["dumbbells","legs","squat","http://www.dumbbell-exercises.com/exercises/legs/images/1.gif"],
  ["dumbbells","legs","reverse lunge","http://www.dumbbell-exercises.com/exercises/legs/images/2.gif"],
  ["dumbbells","legs","stationary lunge","http://www.dumbbell-exercises.com/exercises/legs/images/3.gif"],
  ["dumbbells","legs","side lunge","http://www.dumbbell-exercises.com/exercises/legs/images/4.gif"],
  ["dumbbells","legs","dumbbell swing through","http://www.dumbbell-exercises.com/exercises/legs/images/5.gif"],
  ["dumbbells","legs","stiff legged dead lift","http://www.dumbbell-exercises.com/exercises/legs/images/6.gif"],
  ["dumbbells","legs","calf raise","http://www.dumbbell-exercises.com/exercises/legs/images/7.gif"],
  ["dumbbells","legs","one-legged calf raise","http://www.dumbbell-exercises.com/exercises/legs/images/8.gif"],
  ["dumbbells","legs","seated one-legged calf raise","http://www.dumbbell-exercises.com/exercises/legs/images/9.gif"],
  ["dumbbells","forearms","palms-up wrist curl","http://www.dumbbell-exercises.com/exercises/forearms/images/1.gif"],
  ["dumbbells","forearms","one-arm palm-up wrist curl","http://www.dumbbell-exercises.com/exercises/forearms/images/2.gif"],
  ["dumbbells","forearms","palm-down wrist curl","http://www.dumbbell-exercises.com/exercises/forearms/images/3.gif"],
  ["dumbbells","forearms","one-arm palm-down wrist curl","http://www.dumbbell-exercises.com/exercises/forearms/images/4.gif"],
  ["yoga ball","abs","ball crunch","http://cdn-6.ball-exercises.com/exercises/abs/images/ball-crunch.gif"],
  ["yoga ball","abs"," ball crunch - legs elevated","http://cdn-7.ball-exercises.com/exercises/abs/images/ball-crunch-legs-elevated.gif"],
  ["yoga ball","abs","ball reverse crunch","http://cdn-1.ball-exercises.com/exercises/abs/images/ball-reverse-crunch.gif"],
  ["yoga ball","abs","ball side crunch","http://cdn-7.ball-exercises.com/exercises/abs/images/ball-side-crunch.gif"],
  ["yoga ball","abs","ball sit-up","http://cdn-6.ball-exercises.com/exercises/abs/images/ball-sit-up.gif"],
  ["yoga ball","abs","ball jacknife","http://cdn-3.ball-exercises.com/exercises/abs/images/ball-jacknife.gif"],
  ["yoga ball","abs","ball ab rollout","http://cdn-4.ball-exercises.com/exercises/abs/images/ball-ab-rollout.gif"],
  ["yoga ball","abs","ball table top","http://cdn-6.ball-exercises.com/exercises/abs/images/ball-table-top.gif"],
  ["yoga ball","abs","ball bridge t fall-off","http://cdn-6.ball-exercises.com/exercises/abs/images/ball-bridge-t-fall-off.gif"],
  ["yoga ball","chest","ball dumbbell press","http://cdn-1.ball-exercises.com/exercises/chest/images/ball-dumbbell-press.gif"],
  ["yoga ball","chest","ball dumbbell press - incline","http://cdn-4.ball-exercises.com/exercises/chest/images/ball-dumbbell-press-incline.gif"],
  ["yoga ball","chest","ball push up","http://cdn-2.ball-exercises.com/exercises/chest/images/ball-push-up.gif"],
  ["yoga ball","chest","ball push up - on knees","http://cdn-3.ball-exercises.com/exercises/chest/images/ball-push-up-on-knees.gif"],
  ["yoga ball","chest","ball push up - feet up","http://cdn-1.ball-exercises.com/exercises/chest/images/ball-push-up-feet-up.gif"],
  ["yoga ball","chest","ball chest fly","http://cdn-7.ball-exercises.com/exercises/chest/images/ball-chest-fly.gif"],
  ["yoga ball","chest","ball chest fly - one at a time","http://cdn-0.ball-exercises.com/exercises/chest/images/ball-chest-fly-one-at-a-time.gif"],
  ["yoga ball","chest","ball bear hugs","http://cdn-4.ball-exercises.com/exercises/chest/images/ball-bear-hugs.gif"],
  ["yoga ball","shoulders","ball rear deltoid row","http://cdn-6.ball-exercises.com/exercises/shoulders/images/ball-rear-deltoid-row.gif"],
  ["yoga ball","shoulders","ball rear deltoid raise - elbows bent","http://cdn-4.ball-exercises.com/exercises/shoulders/images/ball-rear-deltoid-raise-elbows-bent.gif"],
  ["yoga ball","shoulders","ball rear deltoid raise - lying sideways","http://cdn-7.ball-exercises.com/exercises/shoulders/images/ball-rear-deltoid-raise-lying-sideways.gif"],
  ["yoga ball","shoulders","ball scapular protraction","http://cdn-3.ball-exercises.com/exercises/shoulders/images/ball-scapular-protraction.gif"],
  ["yoga ball","shoulders","ball shoulder rotation","http://cdn-0.ball-exercises.com/exercises/shoulders/images/ball-shoulder-rotation.gif"],
  ["yoga ball","back","ball hyperextension","http://cdn-6.ball-exercises.com/exercises/back/images/ball-hyperextension.gif"],
  ["yoga ball","back","ball hyperextension - reverse","http://cdn-2.ball-exercises.com/exercises/back/images/ball-hyperextension-reverse.gif"],
  ["yoga ball","back","ball row - upside down","http://cdn-1.ball-exercises.com/exercises/back/images/ball-row-upside-down.gif"],
  ["yoga ball","back","ball bridge","http://cdn-7.ball-exercises.com/exercises/back/images/ball-bridge.gif"],
  ["yoga ball","back","ball arm-leg extension - alternating","http://cdn-0.ball-exercises.com/exercises/back/images/ball-arm-leg-extension-alternating.gif"],
  ["yoga ball","legs","ball squat - on wall","http://cdn-6.ball-exercises.com/exercises/legs/images/ball-squat-wall.gif"],
  ["yoga ball","legs","ball squat - weighted","http://cdn-4.ball-exercises.com/exercises/legs/images/ball-squat-wall-weighted.gif"],
  ["yoga ball","legs","ball squat - sideways","http://cdn-6.ball-exercises.com/exercises/legs/images/ball-squat-wall-sideways-one-legged.gif"],
  ["yoga ball","legs","ball squat - one-legged","http://cdn-1.ball-exercises.com/exercises/legs/images/ball-squat-one-legged.gif"],
  ["yoga ball","legs","ball hip abduction","http://cdn-0.ball-exercises.com/exercises/legs/images/ball-hip-abduction.gif"],
  ["yoga ball","legs","ball hip adduction","http://cdn-1.ball-exercises.com/exercises/legs/images/ball-hip-adduction.gif"],
  ["yoga ball","legs","ball leg curl","http://cdn-1.ball-exercises.com/exercises/legs/images/ball-leg-curl.gif"],
  ["yoga ball","legs","ball reverse leg curl","http://cdn-2.ball-exercises.com/exercises/legs/images/ball-reverse-leg-curl.gif"],
  ["yoga ball","legs","ball squeeze - sitting","http://cdn-7.ball-exercises.com/exercises/legs/images/ball-squeeze-sitting.gif"],
  ["yoga ball","legs","ball squeeze - lying","http://cdn-4.ball-exercises.com/exercises/legs/images/ball-squeeze-lying.gif"],
  ["yoga ball","legs","ball reverse bridge","http://cdn-5.ball-exercises.com/exercises/legs/images/ball-reverse-bridge.gif"],
  ["yoga ball","legs","ball calf raise","http://cdn-2.ball-exercises.com/exercises/legs/images/ball-calf-raise.gif"],
  ["yoga ball","legs","ball calf raise - one-legged","http://cdn-0.ball-exercises.com/exercises/legs/images/ball-calf-raise-one-legged.gif"],
  ["yoga ball","legs","ball toe raise","http://cdn-6.ball-exercises.com/exercises/legs/images/ball-toe-raise.gif"],
  ["yoga ball","biceps","ball biceps curl - standing","http://cdn-6.ball-exercises.com/exercises/arms/images/ball-biceps-curl-standing.gif"],
  ["yoga ball","biceps","ball biceps curl - on knees","http://cdn-2.ball-exercises.com/exercises/arms/images/ball-biceps-curl-knees.gif"],
  ["yoga ball","triceps","ball triceps extension","http://cdn-7.ball-exercises.com/exercises/arms/images/ball-triceps-extension.gif"],
  ["yoga ball","triceps","ball triceps extension - standing","http://cdn-3.ball-exercises.com/exercises/arms/images/ball-triceps-extension-standing.gif"],
  ["yoga ball","triceps","ball triceps extension - weighted","http://cdn-2.ball-exercises.com/exercises/arms/images/ball-triceps-extension-weighted.gif"],
  ["yoga ball","forearms","ball wrist curl","http://cdn-3.ball-exercises.com/exercises/arms/images/ball-wrist-curl.gif"]
];
